# Usar uma imagem base do Python
FROM python:3.9-slim

# Configurar o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do backend para o contêiner
COPY . .

# Instalar dependências do backend
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta do backend
EXPOSE 5000

# Comando para iniciar o backend
CMD ["python", "app.py"]